version: '3'
services:
  products:
    build:
      context: ./products
    environment:
      - PORT=5000
    networks:
      - micro-ecommerce

  orders:
    build:
      context: ./orders
    environment:
      - PORT=5001
    networks:
      - micro-ecommerce

  customers:
    build:
      context: ./customers
    environment:
      - PORT=5002
    networks:
      - micro-ecommerce

networks:
  micro-ecommerce: