version: '3'
services:
  products:
    build:
      context: ./products
    ports:
      - "5000:5000"
    networks:
      - micro-ecommerce

  orders:
    build:
      context: ./orders
    ports:
      - "5001:5000"
    networks:
      - micro-ecommerce

  customers:
    build:
      context: ./customers
    ports:
      - "5002:5000"
    networks:
      - micro-ecommerce

networks:
  micro-ecommerce: